from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

import scripts.regenerate_dependency_locks as regenerate_dependency_locks
import scripts.validate_dependency_locks as validate_dependency_locks


def _lock_header(output_name: str, input_name: str) -> str:
    return (
        "#\n"
        "# This file is autogenerated by pip-compile with Python 3.11\n"
        "# by the following command:\n"
        "#\n"
        f"#    pip-compile --output-file={output_name} {input_name}\n"
        "#\n"
    )


def _write_lock(path: Path, *, input_name: str, package_lines: list[str], trailing: str = "") -> None:
    path.write_text(
        _lock_header(path.name, input_name) + "\n".join(package_lines) + "\n" + trailing,
        encoding="utf-8",
        newline="\n",
    )


def _configure_temp_specs(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    *,
    runtime_input: str = "package-a>=1,<2\n",
    dev_input: str = "-r requirements.in\npip-tools>=7,<8\npytest>=8,<9\n",
    runtime_packages: list[str] | None = None,
    dev_packages: list[str] | None = None,
) -> tuple[Path, Path]:
    runtime_in = tmp_path / "requirements.in"
    dev_in = tmp_path / "requirements-dev.in"
    runtime_lock = tmp_path / "requirements.lock.txt"
    dev_lock = tmp_path / "requirements-dev.lock.txt"
    runtime_text = tmp_path / "requirements.txt"
    dev_text = tmp_path / "requirements-dev.txt"

    runtime_in.write_text(runtime_input, encoding="utf-8", newline="\n")
    dev_in.write_text(dev_input, encoding="utf-8", newline="\n")
    runtime_text.write_text(runtime_input, encoding="utf-8", newline="\n")
    dev_text.write_text(dev_input, encoding="utf-8", newline="\n")

    _write_lock(
        runtime_lock,
        input_name=runtime_in.name,
        package_lines=runtime_packages or ["package-a==1.0"],
    )
    _write_lock(
        dev_lock,
        input_name=dev_in.name,
        package_lines=dev_packages or ["package-a==1.0", "pip-tools==7.5.3", "pytest==8.4.2"],
    )

    runtime_spec = validate_dependency_locks.LockSpec(runtime_in, runtime_lock, runtime_text)
    dev_spec = validate_dependency_locks.LockSpec(dev_in, dev_lock, dev_text)

    monkeypatch.setattr(validate_dependency_locks, "RUNTIME_INPUT", runtime_in)
    monkeypatch.setattr(validate_dependency_locks, "DEV_INPUT", dev_in)
    monkeypatch.setattr(validate_dependency_locks, "RUNTIME_LOCK", runtime_lock)
    monkeypatch.setattr(validate_dependency_locks, "DEV_LOCK", dev_lock)
    monkeypatch.setattr(validate_dependency_locks, "RUNTIME_TEXT", runtime_text)
    monkeypatch.setattr(validate_dependency_locks, "DEV_TEXT", dev_text)
    monkeypatch.setattr(validate_dependency_locks, "LOCK_SPECS", (runtime_spec, dev_spec))
    monkeypatch.setattr(validate_dependency_locks, "require_canonical_lock_environment", lambda action: None)

    return runtime_lock, dev_lock


def test_validate_dependency_locks_static_mode_skips_regeneration(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    _configure_temp_specs(tmp_path, monkeypatch)
    called = False

    def fail_compile(
        input_name: str,
        output_name: str,
        *,
        cwd: Path,
        upgrade: bool,
        quiet: bool,
    ) -> None:
        nonlocal called
        del input_name, output_name, cwd, upgrade, quiet
        called = True
        raise AssertionError("static mode should not regenerate lock files")

    monkeypatch.setattr(validate_dependency_locks, "_compile_lock", fail_compile)

    validate_dependency_locks.validate_locks(mode="static")

    assert called is False


def test_validate_dependency_locks_regenerate_mode_preserves_seeded_pins(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    runtime_lock, dev_lock = _configure_temp_specs(tmp_path, monkeypatch)
    compile_calls: list[tuple[str, str]] = []

    def preserve_seeded_output(
        input_name: str,
        output_name: str,
        *,
        cwd: Path,
        upgrade: bool,
        quiet: bool,
    ) -> None:
        compile_calls.append((input_name, output_name))
        assert upgrade is False
        assert quiet is True
        seeded_output = cwd / output_name
        assert seeded_output.exists()
        assert seeded_output.read_text(encoding="utf-8") in {
            runtime_lock.read_text(encoding="utf-8"),
            dev_lock.read_text(encoding="utf-8"),
        }

    monkeypatch.setattr(validate_dependency_locks, "_compile_lock", preserve_seeded_output)

    validate_dependency_locks.validate_locks(mode="regenerate")

    assert compile_calls == [
        ("requirements.in", "requirements.lock.txt"),
        ("requirements-dev.in", "requirements-dev.lock.txt"),
    ]


def test_validate_dependency_locks_regenerate_mode_detects_constraint_drift_and_reports_diff(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    _configure_temp_specs(tmp_path, monkeypatch)

    def fake_compile(
        input_name: str,
        output_name: str,
        *,
        cwd: Path,
        upgrade: bool,
        quiet: bool,
    ) -> None:
        del upgrade, quiet
        if output_name == "requirements.lock.txt":
            _write_lock(cwd / output_name, input_name=input_name, package_lines=["package-a==1.1"])

    monkeypatch.setattr(validate_dependency_locks, "_compile_lock", fake_compile)

    with pytest.raises(RuntimeError) as excinfo:
        validate_dependency_locks.validate_locks(mode="regenerate")

    message = str(excinfo.value)
    assert "requirements.lock.txt is inconsistent with requirements.in." in message
    assert "Mode: seeded no-upgrade regeneration." in message
    assert "committed/requirements.lock.txt" in message
    assert "generated/requirements.lock.txt" in message
    assert "-package-a==1.0" in message
    assert "+package-a==1.1" in message


def test_validate_dependency_locks_static_mode_detects_added_dependency(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    _configure_temp_specs(
        tmp_path,
        monkeypatch,
        runtime_input="package-a>=1,<2\npackage-b>=2,<3\n",
        runtime_packages=["package-a==1.0"],
        dev_packages=["package-a==1.0", "pip-tools==7.5.3", "pytest==8.4.2"],
    )

    with pytest.raises(RuntimeError, match="missing direct dependencies from requirements.in: \\['package-b'\\]"):
        validate_dependency_locks.validate_locks(mode="static")


def test_validate_dependency_locks_preserves_committed_hashes(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    runtime_lock, dev_lock = _configure_temp_specs(tmp_path, monkeypatch)
    before = {
        runtime_lock.name: hashlib.sha256(runtime_lock.read_bytes()).hexdigest(),
        dev_lock.name: hashlib.sha256(dev_lock.read_bytes()).hexdigest(),
    }

    def fake_compile(
        input_name: str,
        output_name: str,
        *,
        cwd: Path,
        upgrade: bool,
        quiet: bool,
    ) -> None:
        del input_name, upgrade, quiet
        _write_lock(cwd / output_name, input_name=output_name.replace(".lock", ""), package_lines=["package-a==1.1"])

    monkeypatch.setattr(validate_dependency_locks, "_compile_lock", fake_compile)

    with pytest.raises(RuntimeError):
        validate_dependency_locks.validate_locks(mode="regenerate")

    after = {
        runtime_lock.name: hashlib.sha256(runtime_lock.read_bytes()).hexdigest(),
        dev_lock.name: hashlib.sha256(dev_lock.read_bytes()).hexdigest(),
    }
    assert after == before


def test_normalized_lock_text_ignores_line_endings_and_trailing_spaces(tmp_path: Path):
    path_a = tmp_path / "a.lock"
    path_b = tmp_path / "b.lock"
    path_a.write_bytes(b"package-a==1.0\r\npackage-b==2.0  \r\n")
    path_b.write_bytes(b"package-a==1.0\npackage-b==2.0\n")

    assert validate_dependency_locks._normalized_lock_text(path_a) == validate_dependency_locks._normalized_lock_text(path_b)


def test_rewrite_committed_locks_upgrade_updates_packages(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    runtime_lock, dev_lock = _configure_temp_specs(tmp_path, monkeypatch)
    monkeypatch.setattr(validate_dependency_locks, "require_canonical_lock_environment", lambda action: None)

    def fake_compile(
        input_name: str,
        output_name: str,
        *,
        cwd: Path,
        upgrade: bool,
        quiet: bool,
    ) -> None:
        del input_name, quiet
        target = cwd / output_name
        if output_name == runtime_lock.name:
            _write_lock(target, input_name="requirements.in", package_lines=["package-a==1.1"])
        else:
            _write_lock(
                target,
                input_name="requirements-dev.in",
                package_lines=["package-a==1.1", "pip-tools==7.5.3", "pytest==8.4.2"],
            )
        assert upgrade is True

    monkeypatch.setattr(validate_dependency_locks, "_compile_lock", fake_compile)

    changed = validate_dependency_locks.rewrite_committed_locks(upgrade=True)

    assert "requirements.lock.txt: package-a ==1.0 -> ==1.1" in changed
    assert "requirements-dev.lock.txt: package-a ==1.0 -> ==1.1" in changed
    assert runtime_lock.read_text(encoding="utf-8").endswith("package-a==1.1\n")
    assert dev_lock.read_text(encoding="utf-8").endswith("pytest==8.4.2\n")


def test_validate_dependency_locks_parse_args_supports_explicit_modes():
    args = validate_dependency_locks.parse_args(["--mode", "static"])

    assert args.mode == "static"
    assert args.no_regenerate_check is False


def test_regenerate_dependency_locks_parse_args_supports_upgrade_flag():
    args = regenerate_dependency_locks.parse_args(["--upgrade"])

    assert args.upgrade is True
